version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - 3000:80
    security_opt:
      - no-new-privileges
