query LoggedIn {
  loggedIn {
    id
    username
    name
    role
  }
}

mutation Login($data: UserCreateUpdateInput!) {
  login(data: $data) {
    token
    user {
      id
      username
    }
  }
}
