query MyTopTenSeries {
  myTopTenSeries {
    id
    title
    progress {
      id
      overall
    }
  }
}

query MyCurrentlyWatching {
  myCurrentlyWatching {
    id
    title
    episodeCount
    progress {
      id
      completed
    }
  }
}

query CatalogStatistics {
  catalogStatistics {
    totalSeriesCount
    totalEpisodeCount
    allFiles {
      codec
      source
      resolutionHeight
      resolutionWidth
    }
    totalFileSize
    totalDuration
  }
}

query ExportData {
  allSeries {
    title
    seasonNumber
    episodeCount
    status
    type
    releaseSeason
    releaseYear
    remarks
    alternativeTitles {
      title
    }
    episodes {
      title
      episodeNumber
      remarks
      alternativeTitles {
        title
      }
      files {
        path
        fileSize
        checksum
        duration
        resolutionHeight
        resolutionWidth
        source
        codec
        remarks
      }
    }
    prequels {
      title
    }
    sequels {
      title
    }
    sideStories {
      title
    }
    mainStories {
      title
    }
    relatedSeries {
      title
    }
    relatedAlternatives {
      title
    }
    references {
      link
      source
    }
  }
}
