query MyTopTenSeries {
  myTopTenSeries {
    id
    title
    progress {
      overall
    }
  }
}

query MyCurrentlyWatching {
  myCurrentlyWatching {
    id
    title
    episodeCount
    progress {
      completed
    }
  }
}
