query Episode($where: EpisodeWhereUniqueInput!) {
  episode(where: $where) {
    id
    title
    alternativeTitles {
      id
      title
    }
    series {
      id
      title
    }
    episodeNumber
    remarks
    createdAt
    updatedAt
    previous
    next
  }
}

query EpisodesInSeries($where: SeriesWhereUniqueInput!) {
  episodesInSeries(where: $where) {
    id
    title
    episodeNumber
    remarks
  }
}

mutation CreateEpisode($data: EpisodeCreateUpdateInput!) {
  createEpisode(data: $data) {
    id
  }
}

mutation BatchCreateEpisode($data: [EpisodeCreateUpdateInput!]!) {
  batchCreateEpisode(data: $data) {
    id
  }
}

mutation UpdateEpisode(
  $data: EpisodeCreateUpdateInput!
  $where: EpisodeWhereUniqueInput!
) {
  updateEpisode(data: $data, where: $where) {
    id
  }
}

mutation DeleteEpisode($where: EpisodeWhereUniqueInput!) {
  deleteEpisode(where: $where) {
    id
  }
}
