query Series($where: SeriesWhereUniqueInput!) {
    series(where: $where) {
        id
        title
        alternativeTitles {
            id
            title
        }
        episodeCount
        seasonNumber
        releaseSeason
        releaseYear
        remarks
        prequels {
            id
            title
        }
        sequels {
            id
            title
        }
        mainStories {
            id
            title
        }
        sideStories {
            id
            title
        }
    }
}

query AllSeries {
    allSeries {
        id
        title
        seasonNumber
        episodeCount
        type
        status
    }
}

mutation CreateSeries($data: SeriesCreateUpdateInput!) {
    createSeries(data: $data) {
        id
    }
}