query User($where: UserWhereUniqueInput!) {
  user(where: $where) {
    id
    username
    name
  }
}

query Users {
  users {
    id
  }
}

query UserCount {
  userCount
}

mutation CreateUser($data: UserCreateUpdateInput!) {
  createUser(data: $data) {
    id
  }
}

mutation CreateInitialUser($data: UserCreateUpdateInput!) {
  createInitialUser(data: $data) {
    id
  }
}

mutation UpdateMe($data: UserCreateUpdateInput!) {
  updateMe(data: $data) {
    id
  }
}

mutation UpdateUser(
  $where: UserWhereUniqueInput!
  $data: UserCreateUpdateInput!
) {
  updateUser(where: $where, data: $data) {
    id
  }
}

mutation DeleteUser($where: UserWhereUniqueInput!) {
  deleteUser(where: $where) {
    id
  }
}
